import { getSession,getSessionStats,getSlideByAlias,getSlideByHash,patchSession,putSlideAndAliases,updateSlide } from '../core/db.js';
import { MESSAGE,MAX_DATA_URL_BYTES,SOURCE } from '../core/constants.js';
import { dataCaptureIdentity,isLocalDataCapture } from '../core/capture-identity.js';
import { scoreCandidate } from '../core/detector.js';
import { normalizePageNumber } from '../core/page-number.js';
import { originPattern,safeUrl } from '../core/url.js';
import { asErrorMessage,unique } from '../core/utils.js';
import { providerById } from '../providers/index.js';
import { getSettings } from './settings-service.js';
const inflight=new Map();let sequenceCounter=Date.now()*1000;function nextSequence(){sequenceCounter+=1;return sequenceCounter;}function hex(bytes){return[...new Uint8Array(bytes)].map(v=>v.toString(16).padStart(2,'0')).join('');}async function sha256(blob){return hex(await crypto.subtle.digest('SHA-256',await blob.arrayBuffer()));}
function inferExtension(mime,rawUrl){const type=String(mime||'').toLowerCase();if(type.includes('png'))return'png';if(type.includes('webp'))return'webp';if(type.includes('gif'))return'gif';if(type.includes('avif'))return'avif';if(type.includes('svg'))return'svg';if(type.includes('jpeg')||type.includes('jpg'))return'jpg';const url=safeUrl(rawUrl),match=/\.([a-z0-9]{2,5})$/i.exec(url?.pathname||''),ext=match?.[1]?.toLowerCase();return['jpg','jpeg','png','webp','gif','avif','svg'].includes(ext)?(ext==='jpeg'?'jpg':ext):'jpg';}
function dataUrlToBlob(dataUrl){const value=String(dataUrl||'');if(value.length>MAX_DATA_URL_BYTES*1.5)throw new Error('Fallback image is too large');const match=/^data:([^;,]+)?(;base64)?,(.*)$/s.exec(value);if(!match)throw new Error('Invalid image Data URL');const mime=match[1]||'application/octet-stream';if(!mime.startsWith('image/'))throw new Error('Fallback payload is not an image');const body=match[3]||'',binary=match[2]?atob(body):decodeURIComponent(body),bytes=new Uint8Array(binary.length);for(let i=0;i<binary.length;i+=1)bytes[i]=binary.charCodeAt(i);if(bytes.length>MAX_DATA_URL_BYTES)throw new Error('Fallback image is too large');return new Blob([bytes],{type:mime});}
async function fetchWithTimeout(url,options,timeoutMs=20000){const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),timeoutMs);try{return await fetch(url,{...options,signal:controller.signal});}finally{clearTimeout(timer);}}
async function fallbackFetchFromTab(tabId,url){if(!Number.isInteger(tabId)||tabId<0)throw new Error('No tab available for fallback fetch');const response=await chrome.tabs.sendMessage(tabId,{type:MESSAGE.FETCH_RESOURCE_FALLBACK,url});if(!response?.ok||!response?.dataUrl)throw new Error(response?.error||'Page-context fallback failed');return dataUrlToBlob(response.dataUrl);}
async function fetchImageBlob(url,tabId,maxBytes){const errors=[];for(const strategy of [{credentials:'omit',cache:'no-store'},{credentials:'include',cache:'no-store'}]){try{const response=await fetchWithTimeout(url,{method:'GET',redirect:'follow',...strategy,referrerPolicy:'strict-origin-when-cross-origin'});if(!response.ok)throw new Error(`HTTP ${response.status}`);const declared=Number(response.headers.get('content-length')||0);if(declared>maxBytes)throw new Error(`Image exceeds ${maxBytes} bytes`);const blob=await response.blob();if(!blob.size)throw new Error('Image response is empty');if(blob.size>maxBytes)throw new Error(`Image exceeds ${maxBytes} bytes`);return blob;}catch(error){errors.push(asErrorMessage(error));}}try{const blob=await fallbackFetchFromTab(tabId,url);if(blob.size>maxBytes)throw new Error(`Image exceeds ${maxBytes} bytes`);return blob;}catch(error){errors.push(asErrorMessage(error));}throw new Error(`All fetch strategies failed: ${errors.join(' | ')}`);}
function parseSvgDimensions(text){const width=Number(/\bwidth=["']?([0-9.]+)/i.exec(text)?.[1]||0),height=Number(/\bheight=["']?([0-9.]+)/i.exec(text)?.[1]||0);if(width&&height)return{width,height};const viewBox=/\bviewBox=["']?\s*[-0-9.]+\s+[-0-9.]+\s+([0-9.]+)\s+([0-9.]+)/i.exec(text);return{width:Number(viewBox?.[1]||0),height:Number(viewBox?.[2]||0)};}
async function inspectImage(blob,candidate){if(String(blob.type||'').includes('svg')){const d=parseSvgDimensions(await blob.text());return{width:d.width||Number(candidate.width||0),height:d.height||Number(candidate.height||0)};}if(typeof createImageBitmap==='function'){try{const bitmap=await createImageBitmap(blob),result={width:bitmap.width,height:bitmap.height};bitmap.close?.();return result;}catch{}}const width=Number(candidate.width||candidate.renderedWidth||0),height=Number(candidate.height||candidate.renderedHeight||0);if(blob.type.startsWith('image/')&&width&&height)return{width,height};throw new Error(`Unable to decode image (${blob.type||'unknown MIME type'})`);}
function normalizeHint(candidate){const page=normalizePageNumber(candidate.pageHint?.page??candidate.pageHint);return page?{page,confidence:Math.max(0,Math.min(100,Number(candidate.pageHint?.confidence||0))),source:String(candidate.pageHint?.source||'')}:null;}
function mergedHintPatch(slide,hint){if(!hint)return{};const pageHints=Array.isArray(slide.pageHints)?[...slide.pageHints]:[];if(!pageHints.some(item=>item.page===hint.page&&item.source===hint.source))pageHints.push(hint);const currentConfidence=Number(slide.pageConfidence||0);if(!slide.pageHint||hint.confidence>=currentConfidence)return{pageHint:hint.page,pageConfidence:hint.confidence,pageHintSource:hint.source,pageHints};return{pageHints};}
async function markPendingOrigin(sessionKey,pattern,error=''){const current=await getSession(sessionKey),pendingOrigins=unique([...(current?.pendingOrigins||[]),pattern]);return patchSession(sessionKey,{pendingOrigins,lastError:error,lastFailureAt:Date.now()});}
async function clearPendingOrigin(sessionKey,pattern,patch={}){const current=await getSession(sessionKey),pendingOrigins=(current?.pendingOrigins||[]).filter(v=>v!==pattern);return patchSession(sessionKey,{...patch,pendingOrigins});}
async function ensureResourcePermission(session,rawUrl){const pattern=originPattern(rawUrl);if(!pattern)return{granted:false,pattern:null};const granted=await chrome.permissions.contains({origins:[pattern]});if(!granted)await markPendingOrigin(session.sessionKey,pattern,`Permission required for ${pattern}`);return{granted,pattern};}
async function updateDuplicate(slide,candidate,resourceKey){const hint=normalizeHint(candidate),next=await updateSlide(slide.id,{...mergedHintPatch(slide,hint),lastSeenAt:Date.now(),lastSource:candidate.source||slide.lastSource});await putSlideAndAliases(next,[resourceKey]);return next;}
export async function captureCandidate({sessionKey,providerId,candidate},tabId){if(!sessionKey||!candidate?.url)throw new Error('Invalid capture candidate');const session=await getSession(sessionKey);if(!session)throw new Error('Session is not registered');if(session.paused)return{ok:false,skipped:true,reason:'paused'};const settings=await getSettings(),provider=providerById(providerId||session.providerId,settings),resourceKey=provider.canonicalizeResource(candidate.url);if(!resourceKey)throw new Error('Unable to canonicalize resource URL');const existingAlias=await getSlideByAlias(sessionKey,resourceKey);if(existingAlias){const updated=await updateDuplicate(existingAlias,candidate,resourceKey);return{ok:true,duplicate:true,slideId:updated.id};}const permission=await ensureResourcePermission(session,candidate.url);if(!permission.granted)return{ok:false,permissionRequired:true,originPattern:permission.pattern};const inflightKey=`${sessionKey}|${resourceKey}`;if(inflight.has(inflightKey))return inflight.get(inflightKey);const task=(async()=>{try{const blob=await fetchImageBlob(candidate.url,tabId,settings.maxImageBytes),dimensions=await inspectImage(blob,candidate),enriched={...candidate,...dimensions},providerScore=provider.scoreCandidate(enriched),scored=scoreCandidate(enriched,settings,providerScore);if(!scored.accepted&&!provider.isStrongResource(candidate.url)&&candidate.source!==SOURCE.MANUAL)return{ok:false,skipped:true,reason:'low-score',score:scored.score};const contentHash=await sha256(blob),duplicateHash=await getSlideByHash(sessionKey,contentHash);if(duplicateHash){const updated=await updateDuplicate(duplicateHash,candidate,resourceKey);await clearPendingOrigin(sessionKey,permission.pattern);return{ok:true,duplicate:true,slideId:updated.id};}const capturedAt=Date.now(),hint=normalizeHint(candidate),slide={id:`${sessionKey}|${contentHash}`,sessionKey,contentHash,resourceKey,sourceUrl:resourceKey,blob,mime:blob.type||'image/jpeg',ext:inferExtension(blob.type,candidate.url),size:blob.size,width:dimensions.width,height:dimensions.height,pageHint:hint?.page||null,pageConfidence:hint?.confidence||0,pageHintSource:hint?.source||'',pageHints:hint?[hint]:[],providerId:provider.id,source:candidate.source||'unknown',score:scored.score,scoreReasons:scored.reasons,sequence:nextSequence(),capturedAt,createdAt:capturedAt,updatedAt:capturedAt,lastSeenAt:capturedAt};await putSlideAndAliases(slide,[resourceKey]);await clearPendingOrigin(sessionKey,permission.pattern,{lastCaptureAt:capturedAt,lastError:''});return{ok:true,duplicate:false,slideId:slide.id};}catch(error){await patchSession(sessionKey,{lastError:asErrorMessage(error),lastFailureAt:Date.now()});throw error;}finally{inflight.delete(inflightKey);}})();inflight.set(inflightKey,task);return task;}
export async function captureDataUrl({sessionKey,providerId,candidate,dataUrl}){if(!sessionKey||!candidate)throw new Error('Invalid data capture');const session=await getSession(sessionKey);if(!session)throw new Error('Session is not registered');if(session.paused)return{ok:false,skipped:true,reason:'paused'};const settings=await getSettings(),provider=providerById(providerId||session.providerId,settings),blob=dataUrlToBlob(dataUrl);if(blob.size>settings.maxImageBytes)throw new Error('Image exceeds configured size limit');const dimensions=await inspectImage(blob,candidate),enriched={...candidate,...dimensions},localCapture=isLocalDataCapture(candidate),scoringCandidate=localCapture?{...enriched,url:'inline-image.png'}:enriched,providerScore=localCapture?0:provider.scoreCandidate(enriched),scored=scoreCandidate(scoringCandidate,settings,providerScore);if(!scored.accepted&&candidate.source!==SOURCE.MANUAL&&candidate.source!==SOURCE.CANVAS)return{ok:false,skipped:true,reason:'low-score',score:scored.score};const contentHash=await sha256(blob),{resourceKey,sourceUrl}=dataCaptureIdentity(candidate,provider,contentHash),duplicate=await getSlideByHash(sessionKey,contentHash);if(duplicate){const updated=await updateDuplicate(duplicate,candidate,resourceKey);return{ok:true,duplicate:true,slideId:updated.id};}const capturedAt=Date.now(),hint=normalizeHint(candidate),slide={id:`${sessionKey}|${contentHash}`,sessionKey,contentHash,resourceKey,sourceUrl,blob,mime:blob.type||'image/png',ext:inferExtension(blob.type,candidate.url),size:blob.size,width:dimensions.width,height:dimensions.height,pageHint:hint?.page||null,pageConfidence:hint?.confidence||0,pageHintSource:hint?.source||'',pageHints:hint?[hint]:[],providerId:provider.id,source:candidate.source||SOURCE.CANVAS,score:scored.score,scoreReasons:scored.reasons,sequence:nextSequence(),capturedAt,createdAt:capturedAt,updatedAt:capturedAt,lastSeenAt:capturedAt};await putSlideAndAliases(slide,[resourceKey]);await patchSession(sessionKey,{lastCaptureAt:capturedAt,lastError:''});return{ok:true,duplicate:false,slideId:slide.id};}
export async function statusForSession(sessionKey){const[session,stats]=await Promise.all([getSession(sessionKey),getSessionStats(sessionKey)]);return{session,stats};}
