import { fnv1a,matchPatternCovers,sanitizeMatchPattern,urlMatchesPattern } from '../core/url.js';
import { unique } from '../core/utils.js';
const ENABLED_SITES_KEY='enabledSites',SCRIPT_PREFIX='slidecatch_site_';
function normalizeSite(record={}){const pagePatterns=unique((record.pagePatterns||[]).map(sanitizeMatchPattern)),resourcePatterns=unique((record.resourcePatterns||[]).map(sanitizeMatchPattern)),providerId=String(record.providerId||'generic').slice(0,100),siteId=String(record.siteId||`${providerId}:${fnv1a(pagePatterns.join('|'))}`).slice(0,160);return{siteId,providerId,label:String(record.label||siteId).slice(0,160),pagePatterns,resourcePatterns:unique([...pagePatterns,...resourcePatterns]),createdAt:Number(record.createdAt||Date.now()),updatedAt:Date.now()};}
function scriptId(siteId){return `${SCRIPT_PREFIX}${fnv1a(siteId)}`;}
export async function listEnabledSites(){const result=await chrome.storage.local.get(ENABLED_SITES_KEY),values=Array.isArray(result[ENABLED_SITES_KEY])?result[ENABLED_SITES_KEY]:[];return values.map(normalizeSite).filter(site=>site.pagePatterns.length);}
async function saveEnabledSites(sites){await chrome.storage.local.set({[ENABLED_SITES_KEY]:sites.map(normalizeSite)});}
export async function permissionsContainPatterns(patterns){for(const pattern of unique(patterns))if(!(await chrome.permissions.contains({origins:[pattern]})))return false;return true;}
export async function registerSiteContentScript(site){const id=scriptId(site.siteId),existing=await chrome.scripting.getRegisteredContentScripts({ids:[id]}),def={id,matches:site.pagePatterns,js:['content.js'],runAt:'document_start',persistAcrossSessions:true,allFrames:false};if(existing.length)await chrome.scripting.updateContentScripts([def]);else await chrome.scripting.registerContentScripts([def]);}
export async function enableSite(record){const site=normalizeSite(record);if(!site.pagePatterns.length)throw new Error('No valid page permission pattern');const allPatterns=unique([...site.pagePatterns,...site.resourcePatterns]);if(!(await permissionsContainPatterns(allPatterns)))throw new Error('Required host permissions were not granted');const sites=await listEnabledSites(),index=sites.findIndex(item=>item.siteId===site.siteId);if(index>=0)sites[index]={...sites[index],...site,createdAt:sites[index].createdAt};else sites.push(site);await saveEnabledSites(sites);await registerSiteContentScript(site);return site;}
export async function addResourcePatterns(siteId,patterns){const valid=unique((patterns||[]).map(sanitizeMatchPattern));if(!valid.length)return null;if(!(await permissionsContainPatterns(valid)))throw new Error('Resource host permission was not granted');const sites=await listEnabledSites(),index=sites.findIndex(site=>site.siteId===siteId);if(index<0)throw new Error('Enabled site not found');sites[index]=normalizeSite({...sites[index],resourcePatterns:unique([...sites[index].resourcePatterns,...valid])});await saveEnabledSites(sites);return sites[index];}
export async function disableSite(siteId,{removePermissions=true}={}){const sites=await listEnabledSites(),target=sites.find(site=>site.siteId===siteId);if(!target)return false;const remaining=sites.filter(site=>site.siteId!==siteId);await saveEnabledSites(remaining);try{await chrome.scripting.unregisterContentScripts({ids:[scriptId(siteId)]});}catch{}if(removePermissions){const stillUsed=new Set(remaining.flatMap(site=>[...site.pagePatterns,...site.resourcePatterns])),remainingPatterns=[...stillUsed],removable=unique([...target.pagePatterns,...target.resourcePatterns]).filter(pattern=>!stillUsed.has(pattern)&&!remainingPatterns.some(required=>matchPatternCovers(pattern,required)));if(removable.length)await chrome.permissions.remove({origins:removable});}return true;}
export async function findEnabledSiteForUrl(rawUrl){const sites=await listEnabledSites();for(const site of sites){if(!site.pagePatterns.some(pattern=>urlMatchesPattern(rawUrl,pattern)))continue;if(await permissionsContainPatterns(site.pagePatterns))return site;}return null;}
export async function reconcileContentScripts(){const sites=await listEnabledSites(),registered=await chrome.scripting.getRegisteredContentScripts(),expectedIds=new Set(sites.map(site=>scriptId(site.siteId))),staleIds=registered.filter(script=>script.id.startsWith(SCRIPT_PREFIX)&&!expectedIds.has(script.id)).map(script=>script.id);if(staleIds.length)await chrome.scripting.unregisterContentScripts({ids:staleIds});for(const site of sites)if(await permissionsContainPatterns(site.pagePatterns))await registerSiteContentScript(site);}
export async function injectContentScript(tabId){if(!Number.isInteger(tabId)||tabId<0)throw new Error('Invalid tab ID');await chrome.scripting.executeScript({target:{tabId,allFrames:false},files:['content.js']});}
