import { MESSAGE } from '../core/constants.js';
import { localizeDocument,t } from '../core/i18n.js';
localizeDocument();
const $=id=>document.getElementById(id);const fields=['detectionMode','minWidth','minHeight','pollIntervalMs','scanBackgroundImages','captureCanvas','visibleOnly','showOverlay'];let settings={};
async function send(message){return chrome.runtime.sendMessage(message);}
function fill(s){settings=s;for(const id of fields){const el=$(id);if(el.type==='checkbox')el.checked=Boolean(s[id]);else el.value=s[id]??'';}$('maxImageMb').value=Math.round((s.maxImageBytes||0)/1024/1024);$('customProviders').value=JSON.stringify(s.customProviders||[],null,2);}
async function load(){const res=await send({type:MESSAGE.GET_SETTINGS});fill(res.settings||{});await renderSites();}
async function renderSites(){const res=await send({type:MESSAGE.LIST_ENABLED_SITES}),sites=res.sites||[],box=$('sitesList');box.textContent='';$('sitesEmpty').classList.toggle('hidden',sites.length>0);for(const site of sites){const row=document.createElement('div');row.className='site-row';const info=document.createElement('div');info.className='site-info';const title=document.createElement('strong');title.textContent=site.label||site.siteId;const patterns=document.createElement('div');patterns.className='site-patterns';patterns.textContent=[...(site.pagePatterns||[]),...(site.resourcePatterns||[])].join(' · ');info.append(title,patterns);const btn=document.createElement('button');btn.className='danger';btn.textContent=t('revoke',undefined,'Revoke');btn.addEventListener('click',async()=>{if(!confirm(t('confirmRevokeSite',undefined,'Disable this site?')))return;await send({type:MESSAGE.DISABLE_SITE,siteId:site.siteId,removePermissions:true});await renderSites();});row.append(info,btn);box.append(row);}}
$('saveBtn').addEventListener('click',async()=>{try{const customProviders=JSON.parse($('customProviders').value||'[]');$('jsonError').classList.add('hidden');const patch={detectionMode:$('detectionMode').value,minWidth:Number($('minWidth').value),minHeight:Number($('minHeight').value),pollIntervalMs:Number($('pollIntervalMs').value),maxImageBytes:Number($('maxImageMb').value)*1024*1024,scanBackgroundImages:$('scanBackgroundImages').checked,captureCanvas:$('captureCanvas').checked,visibleOnly:$('visibleOnly').checked,showOverlay:$('showOverlay').checked,customProviders};const res=await send({type:MESSAGE.UPDATE_SETTINGS,patch});fill(res.settings||patch);$('saveStatus').textContent=t('saved',undefined,'Saved');setTimeout(()=>$('saveStatus').textContent='',1500);}catch(error){$('jsonError').classList.remove('hidden');$('jsonError').textContent=error.message;}});
$('resetBtn').addEventListener('click',async()=>{if(!confirm(t('confirmReset',undefined,'Reset all settings?')))return;const res=await send({type:MESSAGE.RESET_SETTINGS});fill(res.settings||{});});void load();
