import { MAX_DATA_URL_BYTES, MAX_RESOURCE_URL_LENGTH, MESSAGE, SOURCE } from '../core/constants.js';
import { scoreCandidate } from '../core/detector.js';
import { sanitizeSettings } from '../core/settings.js';
import { fnv1a, safeUrl, urlFamily } from '../core/url.js';
import { asErrorMessage, debounce } from '../core/utils.js';
import { selectProvider } from '../providers/index.js';
import { blobToDataUrl, derivePageHint, isElementVisible, parseBackgroundImageUrls, parseSrcset } from './dom-utils.js';
import { CollectorOverlay } from './overlay.js';

function absoluteUrl(raw){try{return new URL(raw,location.href).href;}catch{return null;}}
function pageTitle(){for(const selector of ['[data-course-title]','[data-lesson-title]','.course-title','.lesson-title','.course-name']){const value=document.querySelector(selector)?.textContent?.trim();if(value&&value.length<200)return value;}const title=document.title?.trim();return title&&title.length<200?title:location.hostname;}
function rectOf(element){const r=element?.getBoundingClientRect?.();return{renderedWidth:Math.round(r?.width||0),renderedHeight:Math.round(r?.height||0)};}

export class SlideCollector{
  constructor(){this.settings=null;this.provider=null;this.session=null;this.paused=false;this.seen=new Map();this.knownUrls=new Set();this.familyMembers=new Map();this.pendingOrigins=new Set();this.stats={count:0,bytes:0,identified:0,missing:[]};this.pollTimer=null;this.routeTimer=null;this.mutationObserver=null;this.performanceObserver=null;this.overlay=null;this.lastLocation=location.href;this.stopped=false;this.canvasCaptureTimes=new WeakMap();this.scanDebounced=debounce(()=>void this.scanDocument(false),180);}
  async send(message){try{return await chrome.runtime.sendMessage(message);}catch(error){return{ok:false,error:asErrorMessage(error)};}}
  async start(){const response=await this.send({type:MESSAGE.GET_SETTINGS});this.settings=sanitizeSettings(response?.settings||{});await this.refreshSession();this.installObservers();this.installMessageHandler();this.installOverlay();await this.scanDocument(true);this.pollTimer=setInterval(()=>void this.scanDocument(false),this.settings.pollIntervalMs);this.routeTimer=setInterval(()=>void this.checkRoute(),1000);}
  stop(){if(this.stopped)return;this.stopped=true;this.paused=true;clearInterval(this.pollTimer);clearInterval(this.routeTimer);this.mutationObserver?.disconnect();this.performanceObserver?.disconnect();this.overlay?.remove();globalThis.__SLIDECATCH_CONTENT_LOADED__=false;if(globalThis.__SLIDECATCH_COLLECTOR__===this)delete globalThis.__SLIDECATCH_COLLECTOR__;}
  async refreshSession(){if(this.stopped)return;this.provider=selectProvider(location.href,this.settings);this.session=this.provider.deriveSession({url:location.href,title:pageTitle()});this.seen.clear();this.knownUrls.clear();this.familyMembers.clear();this.pendingOrigins.clear();const response=await this.send({type:MESSAGE.REGISTER_SESSION,session:this.session});if(response?.status)this.applyStatus(response.status);}
  async checkRoute(){if(location.href===this.lastLocation)return;this.lastLocation=location.href;await this.refreshSession();await this.scanDocument(true);}
  installOverlay(){if(!this.settings.showOverlay)return;this.overlay=new CollectorOverlay({onScan:()=>void this.scanDocument(true),onOpen:()=>void this.send({type:MESSAGE.OPEN_LIBRARY,sessionKey:this.session?.sessionKey})});this.overlay.mount();this.renderOverlay();}
  renderOverlay(error=''){this.overlay?.update({...this.stats,paused:this.paused,pendingOrigins:[...this.pendingOrigins],error});}
  applyStatus(payload){const session=payload?.session||payload?.status?.session,stats=payload?.stats||payload?.status?.stats;if(session?.sessionKey===this.session?.sessionKey){this.paused=Boolean(session.paused);this.pendingOrigins=new Set(session.pendingOrigins||[]);}if(stats)this.stats=stats;this.renderOverlay(session?.lastError||'');}
  installObservers(){this.mutationObserver=new MutationObserver(()=>this.scanDebounced());this.mutationObserver.observe(document.documentElement||document,{childList:true,subtree:true,attributes:true,attributeFilter:['src','srcset','style','class','alt','title','aria-label','data-page','data-page-number','data-slide','data-index']});document.addEventListener('load',event=>{if(event.target instanceof HTMLImageElement)this.processImage(event.target,true);},true);if(typeof PerformanceObserver==='function'){try{this.performanceObserver=new PerformanceObserver(list=>{for(const entry of list.getEntries())this.processPerformanceEntry(entry);});this.performanceObserver.observe({type:'resource',buffered:true});}catch{this.performanceObserver=null;}}}
  installMessageHandler(){chrome.runtime.onMessage.addListener((message,_sender,sendResponse)=>{const run=async()=>{switch(message?.type){case MESSAGE.RESCAN:await this.scanDocument(true);return{ok:true,discovered:this.seen.size};case MESSAGE.REFRESH_SESSION:await this.refreshSession();await this.scanDocument(true);return{ok:true,session:this.session};case MESSAGE.SET_PAUSED:this.paused=Boolean(message.paused);this.renderOverlay();return{ok:true};case MESSAGE.SETTINGS_UPDATED:this.settings=sanitizeSettings(message.settings||{});await this.refreshSession();await this.scanDocument(true);return{ok:true};case MESSAGE.GET_CONTENT_STATE:return{ok:true,session:this.session,paused:this.paused,discovered:this.seen.size,pendingOrigins:[...this.pendingOrigins]};case MESSAGE.STOP_COLLECTOR:this.stop();return{ok:true,stopped:true};case MESSAGE.FETCH_RESOURCE_FALLBACK:return this.fetchResourceFallback(message.url);case MESSAGE.CAPTURE_STATUS:this.applyStatus(message);return{ok:true};default:return{ok:false,error:'Unsupported content message'};}};Promise.resolve(run()).then(sendResponse).catch(error=>sendResponse({ok:false,error:asErrorMessage(error)}));return true;});}
  async scanDocument(force=false){if(this.stopped||!this.session||this.paused)return;for(const img of document.images)this.processImage(img,force);for(const source of document.querySelectorAll('source[srcset]')){const image=source.parentElement?.querySelector?.('img');for(const url of parseSrcset(source.getAttribute('srcset')))this.evaluateCandidate({url,source:SOURCE.SRCSET,width:image?.naturalWidth||0,height:image?.naturalHeight||0,...rectOf(image||source),visible:isElementVisible(image||source),pageHint:derivePageHint(image||source,url,this.provider)},force);}for(const entry of performance.getEntriesByType('resource'))this.processPerformanceEntry(entry,force);if(this.settings.scanBackgroundImages){for(const element of [...document.querySelectorAll('*')].slice(0,5000))this.processBackgroundElement(element,force);}if(this.settings.captureCanvas){for(const canvas of document.querySelectorAll('canvas'))void this.processCanvas(canvas,force);}}
  processImage(img,force=false){if(!(img instanceof HTMLImageElement))return;const urls=new Set([absoluteUrl(img.currentSrc),absoluteUrl(img.src),...parseSrcset(img.getAttribute('srcset'))].filter(Boolean));for(const url of urls)this.evaluateCandidate({url,source:SOURCE.IMAGE,width:img.naturalWidth||Number(img.getAttribute('width'))||0,height:img.naturalHeight||Number(img.getAttribute('height'))||0,...rectOf(img),visible:isElementVisible(img),pageHint:derivePageHint(img,url,this.provider)},force);}
  processBackgroundElement(element,force=false){if(!(element instanceof Element))return;const rect=element.getBoundingClientRect();if(rect.width<250||rect.height<140)return;if(this.settings.visibleOnly&&!isElementVisible(element))return;for(const url of parseBackgroundImageUrls(getComputedStyle(element).backgroundImage))this.evaluateCandidate({url,source:SOURCE.BACKGROUND,width:0,height:0,renderedWidth:Math.round(rect.width),renderedHeight:Math.round(rect.height),visible:isElementVisible(element),pageHint:derivePageHint(element,url,this.provider)},force);}
  processPerformanceEntry(entry,force=false){const url=absoluteUrl(entry?.name);if(!url)return;const type=String(entry.initiatorType||'').toLowerCase();if(!['img','image','css','fetch','xmlhttprequest','other'].includes(type))return;this.evaluateCandidate({url,source:SOURCE.PERFORMANCE,width:0,height:0,renderedWidth:0,renderedHeight:0,visible:true,pageHint:this.provider.extractPageHint({url,text:'',attributes:[]})},force);}
  async processCanvas(canvas,force=false){if(!(canvas instanceof HTMLCanvasElement)||this.paused)return;const now=Date.now(),last=this.canvasCaptureTimes.get(canvas)||0;if(!force&&now-last<7000)return;const width=canvas.width||0,height=canvas.height||0;if(width<this.settings.minWidth||height<this.settings.minHeight)return;if(this.settings.visibleOnly&&!isElementVisible(canvas))return;this.canvasCaptureTimes.set(canvas,now);try{const blob=await new Promise(resolve=>canvas.toBlob(resolve,'image/png'));if(!blob)return;const dataUrl=await blobToDataUrl(blob),candidate={url:`canvas:${location.href}#${[...document.querySelectorAll('canvas')].indexOf(canvas)}`,source:SOURCE.CANVAS,width,height,...rectOf(canvas),visible:isElementVisible(canvas),pageHint:derivePageHint(canvas,location.href,this.provider)};const response=await this.send({type:MESSAGE.CAPTURE_DATA_URL,sessionKey:this.session.sessionKey,providerId:this.provider.id,candidate,dataUrl});if(response?.status)this.applyStatus(response.status);}catch{/* Cross-origin-tainted canvases cannot be serialized. */}}
  evaluateCandidate(candidate,force=false){if(this.stopped||this.paused||!candidate?.url)return;const raw=String(candidate.url||''),inline=/^(?:data|blob):/i.test(raw);if(/^data:/i.test(raw)&&raw.length>MAX_DATA_URL_BYTES*1.5)return;if(!inline&&raw.length>MAX_RESOURCE_URL_LENGTH)return;const parsed=safeUrl(raw,location.href);if(!parsed||!['http:','https:','data:','blob:'].includes(parsed.protocol))return;const url=parsed.href;if(!inline)this.knownUrls.add(url);const family=inline?`${parsed.protocol}inline-image`:urlFamily(url),key=inline?`${parsed.protocol}${url.length}:${fnv1a(url)}`:(this.provider.canonicalizeResource(url)||url),members=this.familyMembers.get(family)||new Set();members.add(key);this.familyMembers.set(family,members);const enriched={...candidate,url,familyCount:members.size},scoringCandidate=inline?{...enriched,url:'inline-image.png'}:enriched,providerScore=inline?0:this.provider.scoreCandidate(enriched),result=scoreCandidate(scoringCandidate,this.settings,providerScore);if(!result.accepted)return;const previous=this.seen.get(key),confidence=Number(enriched.pageHint?.confidence||0);if(!force&&previous&&confidence<=Number(previous.hintConfidence||0)&&Date.now()-previous.sentAt<300000)return;this.seen.set(key,{sentAt:Date.now(),hintConfidence:confidence,score:result.score});if(inline)void this.captureLocalUrl(enriched);else void this.submitCandidate(enriched,key);}
  async captureLocalUrl(candidate){try{const response=await fetch(candidate.url),dataUrl=await blobToDataUrl(await response.blob()),result=await this.send({type:MESSAGE.CAPTURE_DATA_URL,sessionKey:this.session.sessionKey,providerId:this.provider.id,candidate,dataUrl});if(result?.status)this.applyStatus(result.status);}catch(error){this.renderOverlay(asErrorMessage(error));}}
  async submitCandidate(candidate,key){const response=await this.send({type:MESSAGE.CAPTURE_CANDIDATE,sessionKey:this.session.sessionKey,providerId:this.provider.id,candidate});if(response?.permissionRequired&&response.originPattern){this.pendingOrigins.add(response.originPattern);const previous=this.seen.get(key);if(previous)previous.sentAt=0;}if(response?.status)this.applyStatus(response.status);if(!response?.ok&&response?.error)this.renderOverlay(response.error);}
  async fetchResourceFallback(rawUrl){const url=absoluteUrl(rawUrl);if(!url||!this.knownUrls.has(url))return{ok:false,error:'Resource URL was not observed by SlideCatch'};const errors=[];for(const credentials of ['omit','include']){try{const response=await fetch(url,{credentials,cache:'force-cache'});if(!response.ok)throw new Error(`HTTP ${response.status}`);const blob=await response.blob();if(!blob.type.startsWith('image/'))throw new Error('Response is not an image');return{ok:true,dataUrl:await blobToDataUrl(blob)};}catch(error){errors.push(asErrorMessage(error));}}return{ok:false,error:errors.join(' | ')||'Fallback fetch failed'};}
}
