export const APP_ID = 'slidecatch';
export const DB_NAME = 'slidecatch';
export const DB_VERSION = 1;

export const MESSAGE = Object.freeze({
  PING: 'PING', GET_SETTINGS: 'GET_SETTINGS', UPDATE_SETTINGS: 'UPDATE_SETTINGS', RESET_SETTINGS: 'RESET_SETTINGS', SETTINGS_UPDATED: 'SETTINGS_UPDATED',
  ENABLE_SITE: 'ENABLE_SITE', DISABLE_SITE: 'DISABLE_SITE', LIST_ENABLED_SITES: 'LIST_ENABLED_SITES', GET_SITE_STATE: 'GET_SITE_STATE', ADD_RESOURCE_PERMISSIONS: 'ADD_RESOURCE_PERMISSIONS',
  REGISTER_SESSION: 'REGISTER_SESSION', GET_TAB_STATUS: 'GET_TAB_STATUS', GET_SESSION_STATUS: 'GET_SESSION_STATUS', LIST_SESSIONS: 'LIST_SESSIONS', RENAME_SESSION: 'RENAME_SESSION', DELETE_SESSION: 'DELETE_SESSION', CLEAR_SESSION: 'CLEAR_SESSION',
  CAPTURE_CANDIDATE: 'CAPTURE_CANDIDATE', CAPTURE_DATA_URL: 'CAPTURE_DATA_URL', UPDATE_PAGE_HINT: 'UPDATE_PAGE_HINT', DELETE_SLIDE: 'DELETE_SLIDE', RETRY_PENDING: 'RETRY_PENDING',
  RESCAN: 'RESCAN', REFRESH_SESSION: 'REFRESH_SESSION', SET_PAUSED: 'SET_PAUSED', GET_CONTENT_STATE: 'GET_CONTENT_STATE', STOP_COLLECTOR: 'STOP_COLLECTOR', FETCH_RESOURCE_FALLBACK: 'FETCH_RESOURCE_FALLBACK', CAPTURE_STATUS: 'CAPTURE_STATUS', OPEN_LIBRARY: 'OPEN_LIBRARY'
});

export const SOURCE = Object.freeze({ IMAGE: 'image', SRCSET: 'srcset', BACKGROUND: 'background', PERFORMANCE: 'performance', CANVAS: 'canvas', MANUAL: 'manual' });
export const MAX_DATA_URL_BYTES = 16 * 1024 * 1024;
export const MAX_RESOURCE_URL_LENGTH = 32 * 1024;
export const DEFAULT_MAX_IMAGE_BYTES = 30 * 1024 * 1024;
