const POSITIVE_URL_TOKENS = [['slide',4],['slides',4],['ppt',4],['powerpoint',4],['courseware',4],['presentation',3],['deck',3],['page',2],['pages',2],['lecture',2],['lesson',1],['cover',1]];
const NEGATIVE_URL_TOKENS = [['favicon',-10],['avatar',-8],['emoji',-8],['sprite',-8],['logo',-6],['icon',-5],['badge',-4],['tracker',-10],['pixel',-8],['analytics',-8],['advert',-6],['banner',-3],['thumbnail',-1]];
const VOLATILE_QUERY_KEYS = [/^token$/i,/^sig(nature)?$/i,/^expires?$/i,/^auth/i,/^key$/i,/^timestamp$/i,/^ts$/i,/^x-amz-/i,/^x-oss-/i,/^qiniu/i,/^image(mogr|view)/i,/^downloadtoken$/i,/^access[_-]?token$/i,/^bearer$/i,/^credential$/i,/^secret$/i,/^jwt$/i,/^policy$/i,/^key-pair-id$/i,/^x-goog-/i,/^x-ms-/i];
export function safeUrl(raw, base) { try { return new URL(String(raw || ''), base); } catch { return null; } }
export function isHttpUrl(raw, base) { const url = safeUrl(raw, base); return Boolean(url && (url.protocol === 'http:' || url.protocol === 'https:')); }
export function safePageUrl(rawUrl) { const url = safeUrl(rawUrl); if (!url || !['http:','https:'].includes(url.protocol)) return ''; url.username=''; url.password=''; url.search=''; url.hash=''; return url.href; }
export function originPattern(raw) { const url=safeUrl(raw); if (!url || !['http:','https:'].includes(url.protocol)) return null; return `${url.protocol}//${url.hostname}/*`; }
export function fnv1a(input) { let hash=0x811c9dc5; const text=String(input||''); for(let i=0;i<text.length;i+=1){hash^=text.charCodeAt(i);hash=Math.imul(hash,0x01000193);} return (hash>>>0).toString(36); }
export function normalizeSessionPath(pathname) { let p=String(pathname||'/'); p=p.replace(/\/(ppt|slide|slides|page|pages)\/\d+\/?$/i,'/$1').replace(/\/(?:slide|page)[-_]?\d+\/?$/i,'/').replace(/\/\d+\.(?:html?|xhtml)$/i,'/').replace(/\/{2,}/g,'/'); if(p.length>1)p=p.replace(/\/$/,''); return p||'/'; }
export function genericSessionKey(rawUrl) { const url=safeUrl(rawUrl); if(!url)return `generic:${fnv1a(rawUrl)}`; return `generic:${fnv1a(`${url.origin}${normalizeSessionPath(url.pathname)}`)}`; }
export function stripVolatileQuery(rawUrl,{stripAll=false}={}) { const url=safeUrl(rawUrl); if(!url)return String(rawUrl||'').split('#')[0]; url.hash=''; if(stripAll){url.search='';return url.href;} for(const key of [...url.searchParams.keys()]) if(VOLATILE_QUERY_KEYS.some((pattern)=>pattern.test(key))) url.searchParams.delete(key); url.searchParams.sort(); return url.href; }
export function canonicalGenericResource(rawUrl){return stripVolatileQuery(rawUrl);}
export function urlTokenScore(rawUrl){let text=String(rawUrl||'').toLowerCase();try{text=decodeURIComponent(text);}catch{} let score=0;const reasons=[];for(const [token,weight] of POSITIVE_URL_TOKENS)if(text.includes(token)){score+=weight;reasons.push(`url:${token}+${weight}`);}for(const [token,weight] of NEGATIVE_URL_TOKENS)if(text.includes(token)){score+=weight;reasons.push(`url:${token}${weight}`);}return{score,reasons};}
export function urlFamily(rawUrl){const url=safeUrl(rawUrl);if(!url)return String(rawUrl||'').replace(/\d+/g,'#').split('?')[0];const normalized=url.pathname.replace(/[a-f0-9]{16,}/gi,'{hash}').replace(/\d+/g,'{n}').replace(/[^/]+\.(?:jpe?g|png|webp|gif|avif|svg)$/i,'{image}');return `${url.hostname}${normalized}`;}
function escapeRegex(value){return value.replace(/[.*+?^${}()|[\]\\]/g,'\\$&');}
export function matchPatternToRegExp(pattern){if(pattern==='<all_urls>')return /^(?:https?|file|ftp):\/\//i;const match=/^(\*|http|https):\/\/([^/]+)(\/.*)$/.exec(String(pattern||''));if(!match)return null;const[,scheme,host,path]=match;const schemePart=scheme==='*'?'https?':scheme;let hostPart;if(host==='*')hostPart='[^/]+';else if(host.startsWith('*.')){const escapedRoot=escapeRegex(host.slice(2));hostPart=`(?:[^./]+\\.)*${escapedRoot}`;}else hostPart=escapeRegex(host);const pathPart=escapeRegex(path).replace(/\\\*/g,'.*');return new RegExp(`^${schemePart}:\\/\\/${hostPart}(?::\\d+)?${pathPart}$`,'i');}
export function urlMatchesPattern(rawUrl,pattern){const regex=matchPatternToRegExp(pattern);return Boolean(regex&&regex.test(String(rawUrl||'')));}
export function sanitizeMatchPattern(pattern){const value=String(pattern||'').trim();if(!/^(?:http|https):\/\/(?:\*\.)?[A-Za-z0-9.-]+\/\*$/.test(value))return null;if(value.includes('..')||value.includes('@'))return null;return value;}
export function matchPatternCovers(coveringPattern,requiredPattern){const parse=(pattern)=>{const match=/^(http|https):\/\/([^/]+)\/\*$/.exec(String(pattern||''));return match?{scheme:match[1],host:match[2].toLowerCase()}:null;};const covering=parse(coveringPattern),required=parse(requiredPattern);if(!covering||!required||covering.scheme!==required.scheme)return false;if(covering.host==='*'||covering.host===required.host)return true;if(!covering.host.startsWith('*.'))return false;const root=covering.host.slice(2);const requiredHost=required.host.startsWith('*.')?required.host.slice(2):required.host;return requiredHost===root||requiredHost.endsWith(`.${root}`);}
